List products = [
  {
    "id": "1",
    "img": "chicagomain.jpg",
    "name": "Off-White Chicago",
    "price": 4910,
    "stock": 2,
    "amout": "0",
    "mul_img": [
      "chicagomain.jpg",
      "chicago1.jpg",
      "chicago2.jpg",
      "chicago3.jpg"
    ],
    "sizes": [
      "40",
      "41",
      "41,5",
      "42",
      "43",
      "44",
    ],
  },
  {
    "id": "2",
    "img": "nrgmain.jpg",
    "name": "Off-White NRG",
    "price": 1350,
    "stock": 2,
    "amout": "0",
    "mul_img": [
      "nrgmain.jpg",
      "nrg1.jpg",
    ],
    "sizes": [
      "40",
      "41",
      "41,5",
      "42",
      "43",
      "44",
    ],
  },
  {
    "id": "3",
    "img": "uncmain.jpg",
    "name": "Off-White UNC",
    "price": 1460,
    "stock": 2,
    "amout": "0",
    "mul_img": [
      "uncmain.jpg",
      "unc2.jpg",
      "unc1.jpg",
    ],
    "sizes": [
      "40",
      "41",
      "41,5",
      "42",
      "43",
      "44",
    ],
  },
];
